### ISSUE TITLE
Перевести проект на Kotlin

### ISSUE THREAD

**Issue by ensirius** [Ensemplix/Monsoon#1]
Необходимо перевести проект на Kotlin

**Comment by ensirius** [comment]
Проект успешно переведен

**Comment by TeroBlaZe** [comment]
@ensirius Зачем это ._. ? Ради новых ощущений? :))

**Comment by ensirius** [comment]
@TeroBlaZe Kotlin один из наших основных языков. Про плюсы вы можете прочитать здесь - https://kotlinlang.org/

**Comment by TeroBlaZe** [comment]
@ensirius Я так и знал, всё ради того, чтобы в конце не писать;

**Comment by ensirius** [comment]
@TeroBlaZe Я бы не советовал делать таких неоднозначных выводов. Java достаточно старый монстр который мучается со своим legacy и проблемами. Очень много из них решено в этом прекрасном языке.

**Comment by TeroBlaZe** [comment]
@ensirius Да я же в шутку) Мне самому этот язык больше чем скала нравится
